### ISSUE TITLE
Uso de páginas internas

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/fluxo#14]
@eduardozulian querido, estou precisando inserir informações sobre transparência no site da Rede Livre.
Rola liberar as páginas internas?

**Comment by eduardozulian** [comment]
Como foi tudo feito rapidamente, não temos estrutura interna definida. Podemos deixar pro começo da próxima semana?

**Comment by anapaulabrasa** [comment]
Acho que sim, Edu
